name: neurox-env
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36h9745a5d_0
  - cudatoolkit=8.0=3
  - cudnn=7.1.3=cuda8.0_0
  - freetype=2.8=hab7d2ae_1
  - intel-openmp=2018.0.3=0
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.34=hb9fc6fc_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=he85c1e1_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.1=py36h3010b51_0
  - mkl_random=1.0.1=py36h629b387_0
  - nccl=1.3.4=cuda8.0_1
  - ncurses=6.1=hf484d3e_0
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.14.5=py36hcd700cb_2
  - numpy-base=1.14.5=py36hdbf6ddf_2
  - olefile=0.45.1=py36_0
  - openssl=1.0.2o=h20670df_0
  - pillow=5.1.0=py36h3deb7b8_0
  - pip=10.0.1=py36_0
  - pycparser=2.18=py36hf9f622e_1
  - python=3.6.6=hc3d631a_0
  - readline=7.0=ha6073c6_4
  - scikit-learn=0.19.1=py36hedc7406_0
  - scipy=1.1.0=py36hc49cb51_0
  - setuptools=39.2.0=py36_0
  - six=1.11.0=py36h372c433_1
  - sqlite=3.24.0=h84994c4_0
  - tk=8.6.7=hc745277_3
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
  - pytorch=0.4.0=py36_cuda8.0.61_cudnn7.1.2_1
  - torchvision=0.2.1=py36_1
  - pip:
    - chardet==3.0.4
    - click==6.7
    - cycler==0.10.0
    - dill==0.2.8.2
    - flask==1.0.2
    - idna==2.7
    - itsdangerous==0.24
    - jinja2==2.10
    - kiwisolver==1.0.1
    - markupsafe==1.0
    - matplotlib==2.2.3
    - peewee==3.7.1
    - pyparsing==2.2.0
    - python-dateutil==2.7.3
    - pytz==2018.5
    - redis==2.10.6
    - requests==2.19.1
    - torch==0.4.0
    - torchtext==0.3.0
    - tqdm==4.24.0
    - urllib3==1.23
    - walrus==0.6.4
    - werkzeug==0.14.1

